### ISSUE TITLE
Support for Spotify Compilation Albums

### ISSUE THREAD

**Issue by Jeve-Stobs** [Topis-Lavalink-Plugins/Spotify-SourceManager#1]
I was testing this plugin for some api gaps, and I noticed that it doesn't currently support compilation albums. 

For example, fetching a compilation album like this one: https://open.spotify.com/album/5ZxEBTl8KlJ2AEC1dxNTMY?si=wBsGY3qCSfqhj4A2eL3m3A returns 
`Something went wrong when looking up the track`

I have yet to see any implementation of this type of album, so implementing this would make this the first source manager to do so. 

Thanks for maintaining this project!

**Comment by TopiSenpai** [comment]
are you on 1.0.17?
https://github.com/Topis-Lavalink-Plugins/Spotify-SourceManager/releases/tag/v1.0.17

**Comment by Jeve-Stobs** [comment]
Ah, my bad I was on `v1.0.16`. Works as expected. Have a good one!
